CREATE TABLE [dbo].[EXAMPLE2]
(
[IDVENT] [int] NOT NULL IDENTITY(1, 1),
[FECVENT] [datetime] NULL CONSTRAINT [DF__EXAMPLE2__FECVEN__2D27B809] DEFAULT (getdate()),
[ESTVENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__EXAMPLE2__ESTVEN__2E1BDC42] DEFAULT ('A'),
[CANTPER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXAMPLE2] ADD CONSTRAINT [PK__EXAMPLE2__EA675545497AB48D] PRIMARY KEY CLUSTERED ([IDVENT]) ON [PRIMARY]
GO
